const express = require('express')
const app = express()
const cors = require('cors')
const mongoose = require('mongoose')
const ServiceRoute = require("./routes/Service")
app.use(cors())
app.use(express.json())
app.use("/services",ServiceRoute)
app.use("/customer",require('../Back-End/routes/customerRoute'))
app.use("/provider",require('../Back-End/routes/providerRoute'))
app.use("/jobs",require('../Back-End/routes/jobs'))
app.use("/admin",require('../Back-End/routes/Admin'))
app.use("/email",require("./routes/email"))
app.use("/reports",require('../Back-End/routes/Report'))
app.use("/requests",require('../Back-End/routes/requestsRoute'))
mongoose.connect("mongodb+srv://mikgess:melaServices@cluster0.vmzeqwn.mongodb.net/?retryWrites=true&w=majority").then(()=>console.log("Database Connected")).catch((err)=>{
    console.log(err.message)
})
app.listen(5000,()=>[
    console.log("Server is running on port 5000")
])