const mongoose = require("mongoose");
const providerSchema = new mongoose.Schema({
    name:{
        type:String,
        // required:[true,"Please enter a name"],
        default:""
    },
    age:{
        type:Number,
        default:0
    },
    gender:{
        type:String,
        default:""
    },
    password:{
        type:String,
        // required:[true,"Please enter a password"],
        default:""
    },
    email:{
        type:String,
        // required:[true,"Please enter an email"],
        default:""
    },
    rating:{
        type:Number,
        default:0,

    },
    type_of_user:{
        type:String,
        default:""
    },
    completed_profile:{
        type:Boolean,
        default:false
    },
    birr:{
        type:Number,
        default:0
    },
    provider_image:{
        type:String,
        default:""
    },
    provider_description:{
        type:String,
        default:""
    },
    provider_phone:{
        type:String,
        default:""
    },
    status:{
        type:Boolean,
        default:false
    },
    activatedByAdmin:{
        type:Boolean,
        default:true
    },
    verified:{
        type:String,
        default:"pending"
    },
    services:{
        type:Array
    },
    ratedBy:[
        {
            rated_customer:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"customer",
            },
            rateMessage:{
                type:String
            },
            rate:{
                type:Number
            },
            date:{
                type:Date,
                default:Date.now
            }

        }
    ],
    serviceRequest:[
        {
            request_customer_id:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"customer",
            },
            serviceId:{
                type:String
            },
            service_description:{
                type:String,
                required:[true,"Please enter a short description"],
            },
            date:{
                type:Date,
                default:Date.now
            },
            status:{
                type:String,
                default:"pending"
            },
            proceeded_by_Customer:{
                type:Boolean,
                default:false
            },
            
        }
    ],
    location:{
        latitude:{
            type:Number,
            default:""
        },
        longitude:{
            type:Number,
            default:""
        }
    },
    qualifications:[
        {
            qualification:{
                type:String
            }
        }
    ],
    responsiblePersonInfo:
        {
            name:{
                type:String
            },
            phone:{
                type:String
            },
            idPhoto:{
                type:String
            }
        },
    idCardPhoto:{
        type:String
    },
    debts:[
        {
            customer_Info:{
                name:{
                    type:String
                },
                email:{
                    type:String
                },
                customer_id:{
                    type:mongoose.Schema.Types.ObjectId,
                    ref:"customer",
                },
        
            },
            serviceId:{
                type:String
            },
            provider_Info:{
                name:{
                    type:String
                },
                email:{
                    type:String
                },
                provider_id:{
                    type:mongoose.Schema.Types.ObjectId,
                    ref:"provider",
                },
            },
            commission:{
                type:Number
            },  
            date:{
                type:Date,
                default:Date.now
            },
            paid:{
                type:Boolean,
                default:false
                
            }
        }
        ], 
    verificationToken:{
        type:Number,
        default:undefined
    },
    emailVerified:{
        type:Boolean,
        default:false
    }
},

{
    timestamps:true
}
)
module.exports = mongoose.model("provider", providerSchema)